[package]
name = "spreadget"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.9.0"
tokio = "1.17.0"
tokio-tungstenite = "0.17.1"
tonic = "0.6.2"

[build-dependencies]
tonic-build = "0.6.2"
